// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyoksdrpwlukwnklhwru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5b2tzZHJwd2x1a3dua2xod3J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MDUwNDcsImV4cCI6MjA4NjQ4MTA0N30.RO_F-NbFpinn7Ogejt2TeOA2CgXZ32ZdZRdrWq-fPlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});